spring.application.name=reservation-system
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.datasource.url=JDBC:mysql://localhost:3306/Equipment_Booking_DB?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&connectionCollation=utf8_general_ci&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${MySQLPassWord}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
deepseek.api-key=${DEEPSEEK_API_KEY}
//server.port=8080
jwt.expiration=86400000  
